# Generated by Django 2.0.2 on 2019-10-28 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='数据预处理部门')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '数据预处理部门',
                'verbose_name_plural': '数据预处理部门',
            },
        ),
        migrations.AlterModelOptions(
            name='hut_data',
            options={'verbose_name': '数据入库部门', 'verbose_name_plural': '数据入库部门'},
        ),
        migrations.AlterField(
            model_name='hut_data',
            name='name',
            field=models.CharField(max_length=50, verbose_name='数据入库部门'),
        ),
    ]
